name: Build and Push Docker Image with OCI Label

# Trigger the workflow on push to the master branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest  # Choose the OS to run on

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.ACCESS_TOKEN }}

      # Step 4: Build and push the Docker image with OCI 
      - name: Build and push Docker image with OCI label
        run: |
          docker build -t ${{ secrets.USERNAME }}/image1 --label org.opencontainers.image.source="https://github.com/${{ github.repository }}" --push .

      # Step 5: Build and push the Docker image with provenance
      - name: Build and push Image 2 with Provenance
        run: |
          docker buildx build --provenance=true -t ${{ secrets.USERNAME }}/image2 --push .